server:
  name: go-sql-rest-api
  port: 8080

sql:
  data_source_name: root:Nevergiveup4vn.@tcp(127.0.0.1:3306)/masterdata?parseTime=true
  driver: mysql

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
